### ISSUE TITLE
Missing clipboard dependency

### ISSUE THREAD

**Issue by cdaringe** [SolderedElectronics/Soldered-Image-Converter#1]
# problem

`clipboard` not found

# discussion

i added `clipboard==0.0.4` and it booted in a fresh 3.10 venv

**Comment by rsoric** [comment]
Hi @cdaringe 

Thanks, I have [added ](https://github.com/SolderedElectronics/Soldered-Image-Converter/commit/4191accc84feaf0dec7475d463f3f8c87df8ed64)that in requirements.txt in the newly created 'dev' branch so when I get confirmation that this has indeed fixed the issue for future users, I'll close the ticket :)

-Rob
